version: '2'
services:
  web-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/web/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
